services:
    py38:
        image: python:3.8
        volumes:
            - "./:/app"
        working_dir: "/app"
        command: sh scripts/docker-test.sh
    py36:
        extends:
            service: py38
        image: python:3.6
    py37:
        extends:
            service: py38
        image: python:3.7
    py39:
        extends:
            service: py38
        image: python:3.9
    py310:
        extends:
            service: py38
        image: python:3.10
    py311:
        extends:
            service: py38
        image: python:3.11

